version: '3.8'
services:
  app:
    build:
      context: .
      no_cache: true
    ports:
      - "18012:18012"
    volumes:
      - backend_src:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  backend_src: